In [1]:
# 載入函式庫
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [2]:
# 以類型特徵產生特徵矩陣
X = np.array([[0, 2.10, 1.45],
              [1, 1.18, 1.33],
              [0, 1.22, 1.27],
              [1, -0.21, -1.19]])

In [3]:
X

array([[ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

In [4]:
# 以帶有缺漏值之類型特徵產生特徵矩陣
X_with_nan = np.array([[np.nan, 0.87, 1.31],
                       [np.nan, -0.67, -0.22]])

In [5]:
X_with_nan

array([[  nan,  0.87,  1.31],
       [  nan, -0.67, -0.22]])

In [6]:
# 訓練KNN學習器
clf = KNeighborsClassifier(3, weights='distance')
trained_model = clf.fit(X[:,1:], X[:,0])

In [9]:
X[:,1:]

array([[ 2.1 ,  1.45],
       [ 1.18,  1.33],
       [ 1.22,  1.27],
       [-0.21, -1.19]])

In [ ]:
# 預測缺漏值的類型
imputed_values = trained_model.predict(X_with_nan[:,1:])

In [16]:
imputed_values

array([0., 1.])

In [11]:
# 將預測類型的行與其他特徵結合
X_with_imputed = np.hstack((imputed_values.reshape(-1,1), X_with_nan[:,1:]))

In [12]:
X_with_imputed

array([[ 0.  ,  0.87,  1.31],
       [ 1.  , -0.67, -0.22]])

In [13]:
# 結合二特徵矩陣
np.vstack((X_with_imputed, X))

array([[ 0.  ,  0.87,  1.31],
       [ 1.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

In [50]:
# 載入函式庫
#from sklearn.preprocessing import Imputer
from sklearn.impute import SimpleImputer

In [51]:
# 結合特徵矩陣
X_complete = np.vstack((X_with_nan, X))

In [53]:
X_complete[:,0:2]

array([[  nan,  0.87],
       [  nan, -0.67],
       [ 0.  ,  2.1 ],
       [ 1.  ,  1.18],
       [ 0.  ,  1.22],
       [ 1.  , -0.21]])

In [54]:
si=SimpleImputer(strategy="most_frequent")

In [55]:
si.fit(X_complete[:,0:2])

SimpleImputer(strategy='most_frequent')

In [57]:
si.transform(X_complete[:,0:2])

array([[ 0.  ,  0.87],
       [ 0.  , -0.67],
       [ 0.  ,  2.1 ],
       [ 1.  ,  1.18],
       [ 0.  ,  1.22],
       [ 1.  , -0.21]])